name: Health check

on:
  push:
    branches:
      - master 
  schedule:
    - cron: '* * * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://pokedex-hejoel.herokuapp.com/health
          follow-redirect: no
          max-attempts: 3
          retry-delay: 5s